# Generated by Django 3.2.8 on 2021-10-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employeedata',
            fields=[
                ('EmpId', models.AutoField(primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=50)),
                ('EmpMail', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Address', models.TextField()),
            ],
        ),
    ]
